cluster: "sbatch --cpus-per-task={threads} --mem={resources.mem_mb}MB --time=24:00:00 --output=slurm_out/%x-%A --job-name={rule} --parsable"
jobs: 400  # maximum jobs to run at once
latency-wait: 60
restart-times: 1 # number of times to restart failing jobs
